/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/questions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 根据试题 ID 获取详情
         * @description 须 JWT，最低角色 PREMIUM；仅所属题库所有者可查看（ADMIN 可 bypass）。
         *     失败：code=403 角色为 USER；code=404 试题不存在或无权访问。
         */
        get: operations["getById"];
        /**
         * 全量更新试题
         * @description 须 JWT，最低角色 PREMIUM。不可更换所属题库；仅所属题库所有者可更新（ADMIN 可 bypass）。
         *     请求体见 QuestionUpdateDTO（optionsJson/answerJson 为 JSON 数组字符串）。
         *     失败：code=403 角色为 USER；code=404 试题不存在或无权。
         */
        put: operations["update"];
        post?: never;
        /**
         * 删除试题
         * @description 须 JWT，最低角色 PREMIUM。逻辑删除；仅所属题库所有者可删除（ADMIN 可 bypass）。
         *     失败：code=403 角色为 USER；code=404 试题不存在或无权。
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-banks/{bankId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 全量更新题库
         * @description 须 JWT，最低角色 PREMIUM（ADMIN 可 bypass 归属），仅题库所有者可改。成功 data=null。
         *     失败：code=403 角色为 USER；code=404 题库不存在或无权。
         */
        put: operations["updateBank"];
        post?: never;
        /**
         * 删除题库
         * @description 须 JWT，最低角色 PREMIUM（ADMIN 可 bypass 归属），逻辑删除题库并级联逻辑删除其下全部试题。
         *     失败：code=403 角色为 USER；code=404 题库不存在或无权。
         */
        delete: operations["deleteBank"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{userId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 管理端变更用户角色
         * @description 须 JWT，仅 ADMIN。目标角色只允许 USER 或 PREMIUM；禁止设置 ADMIN，禁止修改已有 ADMIN。
         *     失败：code=401 未登录；code=403 非管理员或违反角色变更规则。
         */
        put: operations["updateRole"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用户注册
         * @description **无需登录。** 使用 BCrypt 加密存储密码；服务端固定角色为 `USER`，忽略请求体中的 `role` 字段。
         *     成功：code=200，data 为 null。
         *     失败：code=409 用户名已存在（含已逻辑删除账号）。
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用户登录
         * @description **无需登录。** 校验账号密码，成功返回 JWT 与用户信息（含 `role`：`USER` / `PREMIUM` / `ADMIN`）。
         *     失败：code=401 账号或密码错误。
         *     后续请求 Header：`Authorization: Bearer <token>`。
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-banks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 分页查询当前用户的题库列表
         * @description 须 JWT，最低角色 PREMIUM（ADMIN 可）。Query：`current`、`pageSize`（必填）。仅返回当前用户创建的题库，按更新时间倒序。
         *     失败：code=401 未登录；code=403 角色为 USER。
         */
        get: operations["pageMyBanks"];
        put?: never;
        /**
         * 创建题库
         * @description 须 JWT，最低角色 PREMIUM（ADMIN 可）。成功 data 为新题库 ID（Long）。
         *     失败：code=401 未登录；code=403 角色为 USER。
         */
        post: operations["createBank"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-banks/{bankId}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 分页查询指定题库下的试题
         * @description 须 JWT，最低角色 PREMIUM（ADMIN 可 bypass 归属）。须为题库所有者。Query：`current`、`pageSize`（必填），`keyword`（可选，题干模糊）。
         *     失败：code=403 角色为 USER；code=404 题库不存在或无权。
         */
        get: operations["pageQuestionsInBank"];
        put?: never;
        /**
         * 在指定题库下新增试题
         * @description 须 JWT，最低角色 PREMIUM（ADMIN 可 bypass 归属）。请求体为 QuestionUpdateDTO（含 optionsJson、answerJson 等 JSON 字符串字段），
         *     **勿传 questionBankId**，题库以路径 bankId 为准。
         *     成功 data 为新试题 ID。失败：code=403 角色为 USER；code=404 题库不存在或无权。
         */
        post: operations["createQuestionInBank"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-banks/{bankId}/questions/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 批量确认导入 AI 解析题目（幂等）
         * @description 须 JWT，最低角色 PREMIUM（ADMIN 可 bypass 题库归属）。前端在 `GET .../ai-import/tasks/{taskId}/status` 返回 **PARSED** 且预览确认后调用。
         *
         *     **路径参数**：
         *     - **bankId**：须与任务所属题库一致（路径与任务 meta/DB 记录校验）
         *
         *     **请求体**（`BatchImportRequestDTO`）：
         *     - **taskId**（必填）：submit 或列表/轮询接口获得的 UUID
         *     - **questions**（必填）：用户确认后的题目列表（QuestionPreviewVO；options/answer 为数组）
         *
         *     **预览数据来源优先级**（服务端解析待落库列表时）：
         *     1. MySQL `ai_import_task.preview_json`（权威，关页后可恢复）
         *     2. Redis `ishua:task:result:{taskId}`
         *     3. 请求体 `questions`（若请求体条数明显多于缓存，以缓存为准防重复落库）
         *
         *     **幂等与状态**：
         *     - 已成功 IMPORTED：再次提交 code=200、data=null（幂等成功）
         *     - 并发落库中：code=409「该任务正在导入中，请稍候再试」
         *     - 任务 status=EXPIRED：code=400「任务已过期，请重新上传文件」
         *     - DB 存在且 status 非 PARSED：code=400「任务当前状态不可导入：{status}」
         *     - taskId 在 DB/Redis 均不存在：code=400「任务不存在或已过期」
         *
         *     **成功**：题目写入 `question` 表，任务标记 IMPORTED，清理 Redis 预览缓存。
         *
         *     **失败**：code=401 未登录；code=403（USER 角色、题库无权、task 与 bankId/用户不匹配）；code=400/409 见上
         */
        post: operations["batchImportQuestions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice/banks/{bankId}/questions/{questionId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 提交答案并获取判分结果
         * @description 须 JWT，最低角色 USER。提交指定试题的答案，服务端判分并返回结果。
         *     公开/私有题库访问规则同「获取刷题题目列表」。
         *     - 客观题（SINGLE / MULTI / JUDGE）：自动判分，`correct` 为 true/false。
         *     - 答错时自动将该题加入错题本（若已在错题本中则递增错误次数）。
         *     - 主观题或未知题型：`needsManualGrading=true`，`correct=null`，**不自动加入错题本**。
         *     - 答案与解析在响应的 `answerJson`、`analysis` 字段中返回。
         *     - 用户答案格式：单选/多选传大写字母列表如 `["A"]`、`["A","C"]`；判断题传 `["T"]` 或 `["F"]`。
         *     失败：code=404 题库/试题不存在；code=400 试题不属于该题库；code=403 私有库无权（USER 刷私有库或非所有者）。
         */
        post: operations["submitAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice/banks/{bankId}/questions/{questionId}/reference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查看简答题参考答案
         * @description 须 JWT，最低角色 USER。仅适用于 SHORT_ANSWER（简答题）。
         *     不接收用户答案，不判分，不写错题本。用户在前端本地作答后，点击「显示答案」时调用。
         *     返回 answerJson（JSON 数组字符串，每项为一个要点/段落）与 analysis。
         */
        get: operations["revealReferenceAnswer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai-import/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 提交文件导入任务（异步）
         * @description 须 JWT，最低角色 PREMIUM（ADMIN 含）。`multipart/form-data` 字段：
         *     - **file**（必填）：.txt / .pdf / .docx，最大 10MB
         *     - **bankId**（必填）：目标题库 ID（form 字段；亦可通过 query `?bankId=` 传递，二者等价）
         *
         *     成功立即返回 taskId（status=SUBMITTED），同时写入 MySQL 任务表；后台经 Redis Stream 派发至 Python Worker。
         *     关页恢复：`GET /api/v1/ai-import/tasks` 分页列出本人任务。
         *     轮询：`GET /api/v1/ai-import/tasks/{taskId}/status`。
         *     预览确认入库：`POST /api/v1/question-banks/{bankId}/questions/batch`。
         *
         *     失败：code=400（文件/格式/大小）、401 未登录、403（角色为 USER 或题库无权）、404 题库不存在、429（默认每用户每小时 5 次，见配置 ishua.ai-import.rate-limit）。
         */
        post: operations["submitImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ai-import/tasks/cleanup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 清理长时间未确认的 AI 导入任务
         * @description 须 JWT，**仅 ADMIN**。扫描 MySQL 中 `status=PARSED` 且 `parsed_at` 早于阈值的记录。
         *
         *     **请求体**（`AdminAiImportCleanupDTO`，JSON）：
         *     - **olderThanDays**（可选，默认 7）：清理 `parsed_at < now - N 天` 的任务；范围 1~365
         *     - **bankId**（可选）：仅处理指定题库
         *     - **userId**（可选）：仅处理指定提交用户
         *     - **dryRun**（可选，**默认 true**）：true 时只统计匹配数与样例 taskId，**不写库、不删文件**
         *     - **deleteFiles**（可选，**默认 false**）：dryRun=false 时，是否删除 `file_url` 对应的上传文件
         *     - **maxBatch**（可选，默认 200）：单次最多处理条数，范围 1~1000
         *
         *     **dryRun=false 时的副作用**：
         *     - DB：`status` → `EXPIRED`，写入 `expired_at`、`error_message`，清空 `preview_json`
         *     - Redis：删除 `ishua:task:meta/status/result/import_lock` 相关键
         *     - 用户侧：该 taskId 再调 batch 将返回 code=400「任务已过期」
         *
         *     **响应**（`AdminAiImportCleanupResultVO`）：
         *     - `dryRun`、`matchedCount`、`processedCount`、`sampleTaskIds`（最多 10 条）、`message`
         *
         *     **运维建议**：生产环境先 `dryRun=true` 确认 `matchedCount` 与 `sampleTaskIds`，再 `dryRun=false` 实清。
         *
         *     **失败**：code=401 未登录；code=403 非 ADMIN；code=400（参数校验失败，如 olderThanDays 越界）
         */
        post: operations["cleanupStaleParsedTasks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wrong-questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 分页查询当前用户的错题本
         * @description 须 JWT，最低角色 USER。分页返回当前用户的错题记录，包含题目摘要（不含答案）。
         *     - 可选参数 `bankId`：按题库过滤，不传则返回全部错题。
         *     - 按最近做错时间倒序排列。
         *     返回 `PageResultVO<WrongQuestionVO>`，`total` 为总条数。
         */
        get: operations["pageWrongQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wrong-questions/practice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 按错题本重刷（获取错题刷题列表）
         * @description 须 JWT，最低角色 USER。返回当前用户错题本中所有题目的刷题 VO（不含答案与解析）。
         *     - 可选参数 `bankId`：只返回指定题库的错题，不传则返回全部错题。
         *     - 按最近做错时间倒序排列。
         *     前端拿到题目后仍通过 `POST /api/v1/practice/banks/{bankId}/questions/{questionId}/submit` 提交答案。
         */
        get: operations["listWrongPractice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取当前登录用户信息
         * @description 须 JWT，最低角色 USER。返回 userId、username、nickname、role，供前端按角色渲染菜单。
         *     失败：code=401 未登录或 Token 无效。
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-banks/{bankId}/hot-practice-detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取公开热点题库刷题聚合数据（Redis 缓存）
         * @description **无需登录。** 返回题库信息 + 全量试题（QuestionBankDetailBundleVO）。
         *     仅 is_public=1 的公开题库；失败：code=404 不存在，code=403 非公开题库。
         */
        get: operations["getHotPracticeDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-banks/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 分页查询所有公开题库列表
         * @description **无需登录。** Query：`current`、`pageSize`（必填）。
         *     仅 is_public=1，按更新时间降序，供刷题大厅展示。
         */
        get: operations["pagePublicBanks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice/banks/{bankId}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取刷题题目列表（不含答案）
         * @description 须 JWT，最低角色 USER。返回指定题库的全量试题，**不包含答案与解析**，防止用户提交前获取答案。
         *     - **公开题库**（is_public=1）：任意登录用户可刷，复用 Redis 热点缓存。
         *     - **私有题库**：仅 PREMIUM 且为题库所有者可刷；USER 刷他人或任意私有库 → code=403；ADMIN 可 bypass。
         *     - `random=true` 时随机打乱题目顺序。
         *     答案与解析在提交接口（`POST .../submit`）后返回。
         *     失败：code=404 题库不存在；code=403 私有库无权（含 USER 访问私有库）。
         */
        get: operations["listPracticeQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai-import/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 分页查询当前用户 AI 导入任务
         * @description 须 JWT，最低角色 PREMIUM（ADMIN 含）。用于页面重新打开后恢复「进行中 / 待确认」任务，无需本地保存 taskId。
         *
         *     **Query 参数**（`AiImportTaskPageQueryDTO`，均通过 query 传递）：
         *     - **current**、**pageSize**（必填）：分页，pageSize 上限见全局校验（默认最大 100）
         *     - **bankId**（可选）：仅返回指定题库下的任务
         *     - **status**（可选）：逗号分隔多状态，如 `PARSED,PROCESSING`；合法值：
         *       `SUBMITTED`、`PROCESSING`、`PARSED`、`IMPORTING`、`IMPORTED`、`FAILED`、`EXPIRED`
         *     - **includePreview**（可选，默认 false）：为 true 时，`status=PARSED` 的摘要项携带 `questions[]`（QuestionPreviewVO）
         *
         *     **响应**：`Result<PageResultVO<AiImportTaskSummaryVO>>`
         *     - `data.total`：总条数
         *     - `data.records[]`：当前页摘要（taskId、bankId、fileName、status、message、questionCount、时间戳等）
         *
         *     **前端建议**：
         *     - 导入页 onMounted 调用：`status=PARSED,PROCESSING,SUBMITTED`，展示「待确认 / 解析中」横幅
         *     - `includePreview=true` 时响应体较大，建议 `pageSize` 不超过 10
         *
         *     **失败**：code=401 未登录；code=403 角色为 USER；code=400（status 含非法枚举值）
         */
        get: operations["pageMyTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai-import/tasks/{taskId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 轮询 AI 导入任务状态
         * @description 须 JWT，最低角色 PREMIUM（ADMIN 含）。
         *
         *     **状态流转**：SUBMITTED → PROCESSING → PARSED →（用户确认 batch）→ IMPORTED；
         *     失败为 FAILED；长时间未确认可被管理端清理为 EXPIRED（不可再 batch）。
         *
         *     **数据优先级**（MySQL 持久化后）：
         *     - 任务存在于 MySQL 时，以 DB 状态与 `preview_json` 为准
         *     - DB 中 PARSED 但预览为空时，尝试从 Redis `ishua:task:result:{taskId}` 回填并异步同步回 DB
         *     - 仅 Redis 存在、DB 尚未同步的极短窗口内，回退读 Redis meta/status
         *
         *     **响应字段**（`AiImportTaskStatusVO`）：
         *     - **status**：见上；终态为 IMPORTED、FAILED、EXPIRED
         *     - **message**：失败/过期原因或业务说明
         *     - **totalCount**：解析题目数（PARSED 及之后有意义）
         *     - **questions**：仅 status=PARSED 时填充（QuestionPreviewVO，options/answer 为数组）
         *
         *     **特殊响应**：
         *     - 任务不存在或已彻底过期：code=200 且 **data=null**（非 HTTP 404）
         *     - 无权访问他人任务：code=403
         *
         *     **权限**：仅任务提交者或 ADMIN 可读；USER 在类入口已拦截为 code=403。
         *
         *     **前端建议**：2~5 秒轮询；终态 IMPORTED / FAILED / EXPIRED 后停止；EXPIRED 提示用户重新上传。
         *
         *     **失败**：code=401 未登录；code=403 无权或角色为 USER
         */
        get: operations["getTaskStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 管理端分页查询用户
         * @description 须 JWT，仅 ADMIN。支持按 username 模糊查询、按 role（USER/PREMIUM/ADMIN）精确筛选。
         *     失败：code=401 未登录；code=403 非管理员。
         */
        get: operations["pageUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wrong-questions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 从错题本移除一条记录
         * @description 须 JWT，最低角色 USER，且只能操作本人的错题记录（防止越权）。
         *     执行逻辑删除（is_deleted=1），再次做错该题时会自动复活。
         *     失败：code=404 记录不存在，code=403 无权操作他人记录。
         */
        delete: operations["removeWrongQuestion"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 全量更新试题请求 */
        QuestionUpdateDTO: {
            /**
             * @description 试题题型（接口字段为同名 string，取值见枚举）
             * @example SINGLE
             * @enum {string}
             */
            questionType: "SINGLE" | "MULTI" | "JUDGE" | "SHORT_ANSWER";
            /** @description 题干纯文本 */
            stem: string;
            /**
             * @description 选项 JSON 数组字符串，如 ["选项A","选项B"]
             * @example ["TCP","UDP","IP","ICMP"]
             */
            optionsJson: string;
            /**
             * @description 答案 JSON 数组字符串，如 ["A"]、["A","C"]；判断题 ["T"] 或 ["F"]
             * @example ["A","B"]
             */
            answerJson: string;
            /** @description 题目解析，可选 */
            analysis?: string;
            /**
             * Format: int32
             * @description 题库内排序号，可选；不传则由服务端默认
             */
            sortNo?: number;
        };
        /** @description 全量更新题库请求 */
        QuestionBankUpdateDTO: {
            /**
             * @description 题库名称
             * @example 2026计算机网络期末必刷题
             */
            title: string;
            /**
             * @description 题库描述
             * @example 面向期末周的重点题型整理
             */
            description?: string;
            /**
             * Format: int32
             * @description 是否公开：0-否，1-是
             * @example 1
             */
            isPublic: number;
        };
        /** @description 管理端用户角色更新请求 */
        AdminUserRoleUpdateDTO: {
            /**
             * @description 目标角色，仅允许 USER 或 PREMIUM
             * @example PREMIUM
             */
            role: string;
        };
        /** @description 用户注册请求 */
        UserRegisterDTO: {
            /**
             * @description 登录账号
             * @example zhangsan
             */
            username: string;
            /**
             * @description 登录密码
             * @example 123456
             */
            password: string;
            /**
             * @description 昵称（选填）
             * @example 张三
             */
            nickname?: string;
        };
        /** @description 用户登录请求 */
        UserLoginDTO: {
            /**
             * @description 登录账号
             * @example zhangsan
             */
            username: string;
            /**
             * @description 登录密码
             * @example 123456
             */
            password: string;
        };
        /** @description 用户登录响应 */
        UserLoginVO: {
            /**
             * @description JWT 访问令牌
             * @example eyJhbGciOiJIUzI1NiJ9...
             */
            token?: string;
            /**
             * Format: int64
             * @description 用户 ID
             * @example 1
             */
            userId?: number;
            /**
             * @description 登录账号
             * @example zhangsan
             */
            username?: string;
            /**
             * @description 昵称
             * @example 张三
             */
            nickname?: string;
            /**
             * @description 用户角色：USER-普通用户，PREMIUM-高级用户，ADMIN-管理员
             * @example USER
             */
            role?: string;
        };
        /** @description 创建题库请求 */
        QuestionBankCreateDTO: {
            /**
             * @description 题库名称
             * @example 2026计算机网络期末必刷题
             */
            title: string;
            /**
             * @description 题库描述
             * @example 面向期末周的重点题型整理
             */
            description?: string;
            /**
             * Format: int32
             * @description 是否公开：0-否，1-是
             * @example 1
             */
            isPublic: number;
        };
        /** @description 批量确认导入请求（JSON）。须在任务 status=PARSED 时提交；服务端优先使用 DB/Redis 中的预览缓存落库。 */
        BatchImportRequestDTO: {
            /**
             * @description AI 导入任务 ID（UUID），来自 submit 响应、GET /ai-import/tasks 或 GET .../tasks/{taskId}/status
             * @example a1b2c3d4e5f67890abcdef1234567890
             */
            taskId: string;
            /** @description 经用户预览页确认/编辑后的题目列表；结构与轮询接口 QuestionPreviewVO 一致 */
            questions: components["schemas"]["QuestionPreviewVO"][];
        };
        /**
         * @description AI 预览/批量确认题目（确认导入前可编辑）。
         *     与 QuestionVO 不同：此处 options、answer 为数组；入库后读接口为 optionsJson、answerJson 字符串。
         */
        QuestionPreviewVO: {
            /**
             * @description 试题题型（接口字段为同名 string，取值见枚举）
             * @example SINGLE
             * @enum {string}
             */
            questionType?: "SINGLE" | "MULTI" | "JUDGE" | "SHORT_ANSWER";
            /**
             * @description 题干文本
             * @example 理想气体状态方程 PV=nRT 中，R 的数值是？
             */
            stem?: string;
            /** @description 选项文案列表（判断题固定 ["正确","错误"]） */
            options?: string[];
            /** @description 正确答案：单选 ["B"]；多选 ["A","C"]；判断题 ["T"] 或 ["F"] */
            answer?: string[];
            /** @description 题目解析 */
            analysis?: string;
        };
        /** @description 提交答案请求 */
        AnswerSubmitDTO: {
            /** @description 用户选择的答案列表。单选/多选传大写字母；判断题传 T/F */
            userAnswer: string[];
        };
        /** @description 提交答案判分结果 */
        AnswerSubmitResultVO: {
            /**
             * Format: int64
             * @description 试题 ID
             * @example 50001
             */
            questionId?: number;
            /**
             * @description 是否正确；主观题时为 null
             * @example true
             */
            correct?: boolean;
            /**
             * @description 是否需要人工判分（主观题或未知题型）
             * @example false
             */
            needsManualGrading?: boolean;
            /**
             * @description 标准答案 JSON 数组字符串，如 ["A"]、["T"]
             * @example ["A","C"]
             */
            answerJson?: string;
            /** @description 题目解析（可为空） */
            analysis?: string;
        };
        /** @description AI 导入提交响应 */
        AiImportSubmitVO: {
            /**
             * @description 任务 ID（UUID）
             * @example a1b2c3d4e5f67890abcdef1234567890
             */
            taskId?: string;
            /**
             * @description 初始状态
             * @example SUBMITTED
             */
            status?: string;
        };
        /**
         * @description 管理端 AI 导入任务清理请求（JSON）。仅匹配 status=PARSED 且 parsed_at 早于阈值的记录。
         *     生产环境建议先 dryRun=true 预检，确认 sampleTaskIds 后再 dryRun=false 实清。
         */
        AdminAiImportCleanupDTO: {
            /**
             * Format: int32
             * @description parsed_at 早于「当前时间 − olderThanDays 天」的 PARSED 任务纳入清理范围；不传时服务端默认 7（见配置 ishua.ai-import.cleanup-default-older-than-days）
             * @example 7
             */
            olderThanDays?: number;
            /**
             * Format: int64
             * @description 可选：仅清理指定题库下的任务
             * @example 1001
             */
            bankId?: number;
            /**
             * Format: int64
             * @description 可选：仅清理指定用户提交的任务
             * @example 1
             */
            userId?: number;
            /**
             * @description 是否仅预检：true 只返回 matchedCount 与 sampleTaskIds，不写库；false 执行 EXPIRED 标记与 Redis 清理。不传时视为 true
             * @default true
             * @example true
             */
            dryRun: boolean;
            /**
             * @description 实清（dryRun=false）时是否删除 file_url 指向的上传文件；默认 false，仅清任务与缓存
             * @default false
             * @example false
             */
            deleteFiles: boolean;
            /**
             * Format: int32
             * @description 单次请求最多处理的任务条数，防止长事务；不传时默认 200
             * @default 200
             * @example 200
             */
            maxBatch: number;
        };
        /** @description 管理端 AI 导入任务清理结果（POST /api/v1/admin/ai-import/tasks/cleanup 的 data） */
        AdminAiImportCleanupResultVO: {
            /**
             * @description 本次请求是否为预检（与请求体 dryRun 一致）
             * @example true
             */
            dryRun?: boolean;
            /**
             * Format: int64
             * @description 符合清理条件（PARSED 且 parsed_at 早于阈值）的任务总数，可能大于 processedCount
             * @example 12
             */
            matchedCount?: number;
            /**
             * Format: int32
             * @description 实际处理条数：dryRun=true 时为 0；dryRun=false 时为成功标记 EXPIRED 的条数
             * @example 0
             */
            processedCount?: number;
            /** @description 样例 taskId 列表（最多 10 条），便于运维核对后再实清 */
            sampleTaskIds?: string[];
            /**
             * @description 结果说明，如「dryRun：未执行写操作」或「已清理 N 个长时间未确认任务」
             * @example dryRun：未执行写操作
             */
            message?: string;
        };
        /** @description 错题本记录 */
        WrongQuestionVO: {
            /**
             * Format: int64
             * @description 错题本记录 ID（用于移除操作）
             * @example 1
             */
            id?: number;
            /**
             * Format: int64
             * @description 试题 ID
             * @example 50001
             */
            questionId?: number;
            /**
             * Format: int64
             * @description 所属题库 ID
             * @example 1001
             */
            questionBankId?: number;
            /**
             * @description 试题题型（接口字段为同名 string，取值见枚举）
             * @example SINGLE
             * @enum {string}
             */
            questionType?: "SINGLE" | "MULTI" | "JUDGE" | "SHORT_ANSWER";
            /** @description 题干纯文本 */
            stem?: string;
            /**
             * @description 选项 JSON 数组字符串
             * @example ["TCP","UDP","IP","ICMP"]
             */
            optionsJson?: string;
            /**
             * Format: int32
             * @description 累计做错次数
             * @example 3
             */
            wrongCount?: number;
            /**
             * Format: date-time
             * @description 最近一次做错时间
             */
            lastWrongTime?: string;
        };
        /** @description 刷题模式试题（不含答案与解析） */
        PracticeQuestionVO: {
            /**
             * Format: int64
             * @description 试题主键
             * @example 50001
             */
            id?: number;
            /**
             * Format: int64
             * @description 所属题库 ID
             * @example 1001
             */
            questionBankId?: number;
            /**
             * @description 试题题型（接口字段为同名 string，取值见枚举）
             * @example SINGLE
             * @enum {string}
             */
            questionType?: "SINGLE" | "MULTI" | "JUDGE" | "SHORT_ANSWER";
            /** @description 题干纯文本 */
            stem?: string;
            /**
             * @description 选项 JSON 数组字符串，如 ["TCP","UDP"]；判断题为 []
             * @example ["TCP","UDP","IP","ICMP"]
             */
            optionsJson?: string;
            /**
             * Format: int32
             * @description 题库内排序号
             * @example 1
             */
            sortNo?: number;
        };
        /** @description 简答题参考答案（不含用户作答，不判分） */
        PracticeReferenceAnswerVO: {
            /**
             * Format: int64
             * @description 试题 ID
             * @example 50001
             */
            questionId?: number;
            /**
             * @description 试题题型（接口字段为同名 string，取值见枚举）
             * @example SHORT_ANSWER
             * @enum {string}
             */
            questionType?: "SINGLE" | "MULTI" | "JUDGE" | "SHORT_ANSWER";
            /**
             * @description 参考答案 JSON 数组字符串，每项为一个要点或段落
             * @example ["客户端发 SYN，服务端回 SYN+ACK，客户端再发 ACK"]
             */
            answerJson?: string;
            /** @description 题目解析（可为空） */
            analysis?: string;
        };
        /** @description 当前登录用户信息 */
        UserMeVO: {
            /**
             * Format: int64
             * @description 用户 ID
             * @example 1
             */
            userId?: number;
            /**
             * @description 登录账号
             * @example zhangsan
             */
            username?: string;
            /**
             * @description 昵称
             * @example 张三
             */
            nickname?: string;
            /**
             * @description 用户角色：USER-普通用户，PREMIUM-高级用户，ADMIN-管理员
             * @example USER
             */
            role?: string;
        };
        /** @description 试题信息 */
        QuestionVO: {
            /**
             * Format: int64
             * @description 试题主键
             * @example 50001
             */
            id?: number;
            /**
             * Format: int64
             * @description 所属题库 ID
             * @example 1001
             */
            questionBankId?: number;
            /**
             * @description 试题题型（接口字段为同名 string，取值见枚举）
             * @example SINGLE
             * @enum {string}
             */
            questionType?: "SINGLE" | "MULTI" | "JUDGE" | "SHORT_ANSWER";
            /** @description 题干纯文本 */
            stem?: string;
            /**
             * @description 选项 JSON 数组字符串。单选/多选为选项文案列表，如 ["TCP","UDP","IP"]
             * @example ["8.31 J/(mol·K)","8.31 kJ/(mol·K)","0.0821 L·atm/(mol·K)"]
             */
            optionsJson?: string;
            /**
             * @description 答案 JSON 数组字符串。单选/多选为大写字母选项标，如 ["A"]、["A","C"]；判断题为 ["T"] 或 ["F"]
             * @example ["C"]
             */
            answerJson?: string;
            /** @description 题目解析 */
            analysis?: string;
            /**
             * Format: int32
             * @description 题库内排序号
             * @example 1
             */
            sortNo?: number;
            /**
             * Format: date-time
             * @description 创建时间
             */
            createTime?: string;
            /**
             * Format: date-time
             * @description 更新时间
             */
            updateTime?: string;
        };
        /** @description 题库信息 */
        QuestionBankVO: {
            /**
             * Format: int64
             * @description 题库主键
             * @example 1001
             */
            id?: number;
            /**
             * Format: int64
             * @description 创建者用户 ID
             * @example 20
             */
            userId?: number;
            /**
             * @description 题库名称
             * @example 2026计算机网络期末必刷题
             */
            title?: string;
            /** @description 题库描述 */
            description?: string;
            /**
             * Format: int32
             * @description 是否公开：0=私有，1=公开（公开题库可出现在大厅与热点刷题接口）
             * @example 1
             */
            isPublic?: number;
            /**
             * Format: date-time
             * @description 创建时间
             */
            createTime?: string;
            /**
             * Format: date-time
             * @description 更新时间
             */
            updateTime?: string;
        };
        /** @description 热点题库详情（含全量试题） */
        QuestionBankDetailBundleVO: {
            bank?: components["schemas"]["QuestionBankVO"];
            /** @description 该题库下全部试题（按 sortNo 有序；含答案与解析） */
            questions?: components["schemas"]["QuestionVO"][];
        };
        /** @description AI 导入任务列表单条摘要（用于 GET /api/v1/ai-import/tasks 的 data.records[]） */
        AiImportTaskSummaryVO: {
            /**
             * @description 业务任务 ID（UUID），与轮询、batch 接口一致
             * @example a1b2c3d4e5f67890abcdef1234567890
             */
            taskId?: string;
            /**
             * Format: int64
             * @description 目标题库 ID
             * @example 1001
             */
            bankId?: number;
            /**
             * @description 用户上传时的原始文件名
             * @example 期末复习.pdf
             */
            fileName?: string;
            /**
             * @description 任务状态：SUBMITTED、PROCESSING、PARSED、IMPORTING、IMPORTED、FAILED、EXPIRED。
             *     PARSED 表示可进入预览确认；EXPIRED 表示已过期清理，需重新 submit。
             * @example PARSED
             */
            status?: string;
            /**
             * @description FAILED/EXPIRED 时的原因摘要，或成功态业务说明；可为空
             * @example 解析完成，待确认导入
             */
            message?: string;
            /**
             * Format: int32
             * @description 解析出的题目数量；PARSED 及之后有意义
             * @example 42
             */
            questionCount?: number;
            /**
             * Format: date-time
             * @description 任务提交时间
             */
            submittedAt?: string;
            /**
             * Format: date-time
             * @description 进入 PARSED 的时间；未解析完成时为 null
             */
            parsedAt?: string;
            /**
             * Format: date-time
             * @description 确认 batch 落库完成时间；未导入时为 null
             */
            importedAt?: string;
            /**
             * Format: date-time
             * @description 被管理端清理为 EXPIRED 的时间；未过期时为 null
             */
            expiredAt?: string;
            /** @description 预览题目列表；仅查询参数 includePreview=true 且本条 status=PARSED 时非空 */
            questions?: components["schemas"]["QuestionPreviewVO"][];
        };
        /** @description AI 导入任务状态快照 */
        AiImportTaskStatusVO: {
            /** @description 任务 ID（UUID） */
            taskId?: string;
            /**
             * @description 任务状态：SUBMITTED（已入队）→ PROCESSING（解析中）→ PARSED（可预览）→
             *     IMPORTING（落库中，可选）→ IMPORTED（完成）、FAILED（失败）或 EXPIRED（长时间未确认已过期）
             * @example PARSED
             */
            status?: string;
            /** @description FAILED/EXPIRED 时的错误摘要，或业务说明；成功流转中常为空 */
            message?: string;
            /**
             * Format: int32
             * @description 解析出的题目总数；status=PARSED 时通常等于 questions.length
             * @example 42
             */
            totalCount?: number;
            /**
             * @description 预览题目列表。status=PARSED 时返回（优先 MySQL preview_json，其次 Redis result）。
             *     终态 IMPORTED/FAILED/EXPIRED 时不返回或为空。
             */
            questions?: components["schemas"]["QuestionPreviewVO"][];
        };
        /** @description 管理端用户列表项 */
        AdminUserVO: {
            /**
             * Format: int64
             * @description 用户 ID
             * @example 1
             */
            userId?: number;
            /**
             * @description 登录账号
             * @example zhangsan
             */
            username?: string;
            /**
             * @description 昵称
             * @example 张三
             */
            nickname?: string;
            /**
             * @description 用户角色：USER-普通用户，PREMIUM-高级用户，ADMIN-管理员
             * @example USER
             */
            role?: string;
            /**
             * Format: date-time
             * @description 创建时间
             */
            createTime?: string;
            /**
             * Format: date-time
             * @description 更新时间
             */
            updateTime?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 试题主键
                 * @example 50001
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        data?: components["schemas"]["QuestionVO"];
                    };
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 试题主键
                 * @example 50001
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionUpdateDTO"];
            };
        };
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        /** @description 无业务数据（成功时亦为 null） */
                        data?: unknown;
                    };
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 试题主键
                 * @example 50001
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        /** @description 无业务数据（成功时亦为 null） */
                        data?: unknown;
                    };
                };
            };
        };
    };
    updateBank: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 题库 ID
                 * @example 1001
                 */
                bankId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionBankUpdateDTO"];
            };
        };
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        /** @description 无业务数据（成功时亦为 null） */
                        data?: unknown;
                    };
                };
            };
        };
    };
    deleteBank: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 题库 ID
                 * @example 1001
                 */
                bankId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        /** @description 无业务数据（成功时亦为 null） */
                        data?: unknown;
                    };
                };
            };
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 目标用户 ID
                 * @example 2
                 */
                userId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserRoleUpdateDTO"];
            };
        };
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        /** @description 无业务数据（成功时亦为 null） */
                        data?: unknown;
                    };
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegisterDTO"];
            };
        };
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        /** @description 无业务数据（成功时亦为 null） */
                        data?: unknown;
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLoginDTO"];
            };
        };
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        data?: components["schemas"]["UserLoginVO"];
                    };
                };
            };
        };
    };
    pageMyBanks: {
        parameters: {
            query: {
                /**
                 * @description 当前页码，从 1 开始
                 * @example 1
                 */
                current: number;
                /**
                 * @description 每页条数
                 * @example 10
                 */
                pageSize: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        /** @description 分页响应：total + records（字段名固定为 records） */
                        data?: {
                            /**
                             * Format: int64
                             * @description 总记录数
                             * @example 100
                             */
                            total?: number;
                            /** @description 当前页数据列表 */
                            records?: components["schemas"]["QuestionBankVO"][];
                        } | null;
                    };
                };
            };
        };
    };
    createBank: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionBankCreateDTO"];
            };
        };
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        /**
                         * Format: int64
                         * @description 新建资源主键 ID
                         * @example 1001
                         */
                        data?: number | null;
                    };
                };
            };
        };
    };
    pageQuestionsInBank: {
        parameters: {
            query: {
                /** @description 题干关键词模糊检索，可选 */
                keyword?: string;
                /**
                 * @description 当前页码，从 1 开始
                 * @example 1
                 */
                current: number;
                /**
                 * @description 每页条数
                 * @example 10
                 */
                pageSize: number;
            };
            header?: never;
            path: {
                /**
                 * @description 题库 ID
                 * @example 1001
                 */
                bankId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        /** @description 分页响应：total + records（字段名固定为 records） */
                        data?: {
                            /**
                             * Format: int64
                             * @description 总记录数
                             * @example 100
                             */
                            total?: number;
                            /** @description 当前页数据列表 */
                            records?: components["schemas"]["QuestionVO"][];
                        } | null;
                    };
                };
            };
        };
    };
    createQuestionInBank: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 题库 ID
                 * @example 1001
                 */
                bankId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionUpdateDTO"];
            };
        };
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        /**
                         * Format: int64
                         * @description 新建资源主键 ID
                         * @example 1001
                         */
                        data?: number | null;
                    };
                };
            };
        };
    };
    batchImportQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 题库 ID
                 * @example 1001
                 */
                bankId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchImportRequestDTO"];
            };
        };
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        /** @description 无业务数据（成功时亦为 null） */
                        data?: unknown;
                    };
                };
            };
        };
    };
    submitAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 题库 ID
                 * @example 1001
                 */
                bankId: number;
                /**
                 * @description 试题 ID
                 * @example 50001
                 */
                questionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerSubmitDTO"];
            };
        };
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        data?: components["schemas"]["AnswerSubmitResultVO"];
                    };
                };
            };
        };
    };
    revealReferenceAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 题库 ID
                 * @example 1001
                 */
                bankId: number;
                /**
                 * @description 试题 ID
                 * @example 50001
                 */
                questionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        data?: components["schemas"]["PracticeReferenceAnswerVO"];
                    };
                };
            };
        };
    };
    submitImport: {
        parameters: {
            query: {
                /**
                 * @description 目标题库 ID（须为当前用户所属题库）
                 * @example 1001
                 */
                bankId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        data?: components["schemas"]["AiImportSubmitVO"];
                    };
                };
            };
        };
    };
    cleanupStaleParsedTasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminAiImportCleanupDTO"];
            };
        };
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        data?: components["schemas"]["AdminAiImportCleanupResultVO"];
                    };
                };
            };
        };
    };
    pageWrongQuestions: {
        parameters: {
            query: {
                /**
                 * @description 按题库 ID 过滤，不传则查询全部错题
                 * @example 1001
                 */
                bankId?: number;
                /**
                 * @description 当前页码，从 1 开始
                 * @example 1
                 */
                current: number;
                /**
                 * @description 每页条数
                 * @example 10
                 */
                pageSize: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        /** @description 分页响应：total + records（字段名固定为 records） */
                        data?: {
                            /**
                             * Format: int64
                             * @description 总记录数
                             * @example 100
                             */
                            total?: number;
                            /** @description 当前页数据列表 */
                            records?: components["schemas"]["WrongQuestionVO"][];
                        } | null;
                    };
                };
            };
        };
    };
    listWrongPractice: {
        parameters: {
            query?: {
                /**
                 * @description 按题库 ID 过滤，不传则返回全部错题
                 * @example 1001
                 */
                bankId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        /** @description 列表数据 */
                        data?: components["schemas"]["PracticeQuestionVO"][] | null;
                    };
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        data?: components["schemas"]["UserMeVO"];
                    };
                };
            };
        };
    };
    getHotPracticeDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 题库 ID
                 * @example 1
                 */
                bankId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        data?: components["schemas"]["QuestionBankDetailBundleVO"];
                    };
                };
            };
        };
    };
    pagePublicBanks: {
        parameters: {
            query: {
                /**
                 * @description 当前页码，从 1 开始
                 * @example 1
                 */
                current: number;
                /**
                 * @description 每页条数
                 * @example 10
                 */
                pageSize: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        /** @description 分页响应：total + records（字段名固定为 records） */
                        data?: {
                            /**
                             * Format: int64
                             * @description 总记录数
                             * @example 100
                             */
                            total?: number;
                            /** @description 当前页数据列表 */
                            records?: components["schemas"]["QuestionBankVO"][];
                        } | null;
                    };
                };
            };
        };
    };
    listPracticeQuestions: {
        parameters: {
            query?: {
                /**
                 * @description 是否随机打乱题目顺序，默认 false（按 sortNo 顺序）
                 * @example false
                 */
                random?: boolean;
            };
            header?: never;
            path: {
                /**
                 * @description 题库 ID
                 * @example 1001
                 */
                bankId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        /** @description 列表数据 */
                        data?: components["schemas"]["PracticeQuestionVO"][] | null;
                    };
                };
            };
        };
    };
    pageMyTasks: {
        parameters: {
            query: {
                /**
                 * @description 目标题库 ID；不传则返回用户全部题库下的任务
                 * @example 1001
                 */
                bankId?: number;
                /**
                 * @description 任务状态筛选，逗号分隔多值。合法值：SUBMITTED、PROCESSING、PARSED、IMPORTING、IMPORTED、FAILED、EXPIRED。
                 *     不传则不过滤状态。前端恢复场景常用：PARSED,PROCESSING,SUBMITTED
                 * @example PARSED,PROCESSING
                 */
                status?: string;
                /**
                 * @description 是否在列表项中携带预览题目（questions[]）。默认 false。
                 *     仅对 status=PARSED 的记录填充；响应体较大，建议 pageSize≤10。
                 * @example false
                 */
                includePreview?: boolean;
                /**
                 * @description 当前页码，从 1 开始
                 * @example 1
                 */
                current: number;
                /**
                 * @description 每页条数
                 * @example 10
                 */
                pageSize: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        /** @description 分页响应：total + records（字段名固定为 records） */
                        data?: {
                            /**
                             * Format: int64
                             * @description 总记录数
                             * @example 100
                             */
                            total?: number;
                            /** @description 当前页数据列表 */
                            records?: components["schemas"]["AiImportTaskSummaryVO"][];
                        } | null;
                    };
                };
            };
        };
    };
    getTaskStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 提交接口返回的任务 ID（UUID） */
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        data?: components["schemas"]["AiImportTaskStatusVO"];
                    };
                };
            };
        };
    };
    pageUsers: {
        parameters: {
            query: {
                /**
                 * @description 用户名关键字（可选）
                 * @example zhang
                 */
                username?: string;
                /**
                 * @description 角色筛选：USER/PREMIUM/ADMIN（可选）
                 * @example USER
                 */
                role?: string;
                /**
                 * @description 当前页码，从 1 开始
                 * @example 1
                 */
                current: number;
                /**
                 * @description 每页条数
                 * @example 10
                 */
                pageSize: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        /** @description 分页响应：total + records（字段名固定为 records） */
                        data?: {
                            /**
                             * Format: int64
                             * @description 总记录数
                             * @example 100
                             */
                            total?: number;
                            /** @description 当前页数据列表 */
                            records?: components["schemas"]["AdminUserVO"][];
                        } | null;
                    };
                };
            };
        };
    };
    removeWrongQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 错题本记录 ID
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description HTTP 200。成功时 body.code=200 且 data 有值（Void 接口 data 为 null）。
             *     业务失败时 HTTP 仍为 200，body.code 见接口说明（常见 400/401/403/404/409/429/500），data 多为 null。
             *     响应 body 的 data 字段结构见本接口 Schema 示例（已按泛型展开）。
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int32
                         * @description 业务状态码：200 成功；4xx/5xx 为业务失败（HTTP 仍多为 200）
                         * @example 200
                         */
                        code?: number;
                        /**
                         * @description 提示信息
                         * @example success
                         */
                        message?: string;
                        /** @description 无业务数据（成功时亦为 null） */
                        data?: unknown;
                    };
                };
            };
        };
    };
}
